MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "pretrained_models/xv_test2.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 200
    FPN_POST_NMS_TOP_N_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 512
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 1024
    POSITIVE_FRACTION: 0.5
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 63
DATASETS:
  TRAIN: ("xview_train_aug",)
  TEST: ("xview_val_orig",)
INPUT:
  MIN_SIZE_TRAIN: (500,)
  MAX_SIZE_TRAIN: 900
  MIN_SIZE_TEST: 500
  MAX_SIZE_TEST: 900
OUTPUT_DIR: "results/aug"
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (70000, 90000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 4
