MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "pretrained_models/xv_test2.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (16, 32, 64, 128, 256)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 200
    FPN_POST_NMS_TOP_N_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 512
    OBJECTNESS_LOSS_FN: "ReducedFocal"
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 1024
    POSITIVE_FRACTION: 0.5
    CLASSIFICATION_LOSS_FN: "CE"
    DETECTIONS_PER_IMG: 200
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 63
DATASETS:
  TRAIN: ("xview_train_8020",)
  TEST: ("xview_val_8020",)
INPUT:
  MIN_SIZE_TRAIN: (700,)
  MAX_SIZE_TRAIN: 700
  MIN_SIZE_TEST: 700
  MAX_SIZE_TEST: 700
  BRIGHTNESS: 0.25
  SATURATION: 0.25
  HUE: 0.25
OUTPUT_DIR: "results/8020-small-anchors-rpnrfl"
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (70000, 90000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 2
